java_test(
    name = "InMemoryLogTest",
    srcs = ["InMemoryLogTest.java"],
    deps = ["@org_junit_junit_4_12//jar"],
)

java_test(
    name = "PersistentLogTest",
    srcs = ["PersistentLogTest.java"],
    deps = ["@org_junit_junit_4_12//jar"],
)