java_test(
    name = "InMemoryLogTest",
    srcs = ["InMemoryLogTest.java"],
    deps = ["//third_party/junit"],
)

java_test(
    name = "PersistentLogTest",
    srcs = ["PersistentLogTest.java"],
    deps = ["//third_party/junit"],
)