java_test(
    name = "AcceptorTest",
    srcs = ["AcceptorTest.java"],
    deps = ["//third_party/junit"],
)

java_test(
    name = "NodeTest",
    srcs = ["NodeTest.java"],
    deps = ["//third_party/junit"],
)

java_test(
    name = "PaxosGroupTest",
    srcs = ["PaxosGroupTest.java"],
    deps = ["//java/com/yaoshengzhe/paxos:paxos_group",
            "//third_party/guice",
            "//java/com/yaoshengzhe/paxos:paxos_module",
            "//java/com/yaoshengzhe/paxos:node",
            "//third_party/truth",
            "//third_party/junit"],
)

java_test(
    name = "ProposerTest",
    srcs = ["ProposerTest.java"],
    deps = ["//third_party/junit"],
)