package(default_visibility = ["//src/com/yaoshengzhe/paxos:__subpackages__"])

java_library(
    name = "in_memory_log",
    srcs = ["InMemoryLog.java"],
    deps = [":persistent_log"],
)

java_library(
    name = "persistent_log",
    srcs = ["PersistentLog.java"],
)
